site_name: neuro_pypes
pages:
    - Home: index.md
    - Getting started: getting_started.md
    - Configuration: configuration.md
    - Command line: cli.md
    - Preprocessing: preprocessing.md
    - Independent-components: ICA.md
    - Connectivity: connectivity.md
    - Tractography: tractography.md
    - Plotting: plotting.md
    - External interfaces: external_interfaces.md
    - Datasets: datasets.md
    - About: about.md
    - License: license.md
theme: readthedocs
