# ----------------------------------------------------------------------
# TUM Clinical pypes configuration parameters
# ----------------------------------------------------------------------

## global configuration parameters
normalize_atlas: True
atlas_file: '' # this is being set from config.py


# ANAT


# DTI
coreg_b0.write_interp: 3


# REST
coreg_rest.write_interp: 3

## the last volume index to discard from the timeseries. default: 0
trim.begin_index: 5

# bandpass filter frequencies in Hz.
rest_input.lowpass_freq: 0.08 # the numerical upper bound
rest_input.highpass_freq: 0.01 # the numerical lower bound

# fwhm of smoothing kernel [mm]
smooth_fmri.fwhm: 8

## CompCor rsfMRI filters (at least compcor_csf should be True).
rest_filter.compcor_csf: True
rest_filter.compcor_wm: True
rest_filter.gsr: False

# filters parameters
## the corresponding filter must be enabled for these.

# motion regressors upto given order and derivative
# motion + d(motion)/dt + d2(motion)/dt2 (linear + quadratic)
motion_regressors.order: 0
motion_regressors.derivatives: 1

# number of polynomials to add to detrend
motart_parameters.detrend_poly: 2

# Threshold to use to detect motion-related outliers when composite motion is being used
detect_artifact.norm_threshold: 1
detect_artifact.parameter_source: NiPy
detect_artifact.mask_type: spm_global

# Number of principal components to calculate when running CompCor. 5 or 6 is recommended.
compcor_pars.num_components: 5

# Number of principal components to calculate when running Global Signal Regression. 1 is recommended.
gsr_pars.num_components: 1

# REST CONNECTIVITY
## if atlas_file is defined, perform connectivity analysis
rest_preproc.connectivity: True

## if further smoothing (remember the output of the rest workflow is already smoothed)
rest_connectivity.standardize: False
rest_connectivity.kind: correlation # choices: "correlation", "partial correlation", "tangent", "covariance", "precision".
#rest_connectivity.smoothing_fwhm: 8
#rest_connectivity.resampling_target: # choices: "mask", "maps" or undefined.
rest_connectivity.atlas_type: labels # choices: "labels", "probabilistic".


# REST (COBRE DB)
# http://fcon_1000.projects.nitrc.org/indi/retro/cobre.html
# Rest scan:
# - collected in the Axial plane,
# - series ascending,
# - multi slice mode and
# - interleaved.
stc_input.slice_mode: alt_inc
stc_input.time_repetition: 2
stc_input.num_slices: 33

# PET PVC
rbvpvc.pvc: RBV
rbvpvc.fwhm_x: 4.3
rbvpvc.fwhm_y: 4.3
rbvpvc.fwhm_z: 4.3