# ----------------------------------------------------------------------
# TUM Clinical pypes configuration parameters
# ----------------------------------------------------------------------

# ANAT


# DTI
dti_input.atlas_file: '' # this is being set from config.py


# REST
trim.begin_index: 6


# PET PVC
rbvpvc.pvc: RBV
rbvpvc.fwhm_x: 4.3
rbvpvc.fwhm_y: 4.3
rbvpvc.fwhm_z: 4.3